package com.easyparking.dao;

import com.easyparking.entity.CarInfo;


 
/**
 * DAO interface for table: CarInfo.
 * @author autogenerated
 */
public class CarInfoDao extends GenericDao< Integer,CarInfo> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// constructor only
}

