package com.easyparking.dao;

import com.easyparking.entity.ParkingLot;

 
/**
 * DAO interface for table: ParkingLot.
 * @author autogenerated
 */
public class ParkingLotDao extends GenericDao<Integer,ParkingLot>  {
	// constructor only
}

