package com.easyparking.dao;

import org.springframework.transaction.annotation.Transactional;

import com.easyparking.entity.User;
import com.easyparking.util.EasyParkingException;

 
/**
 * DAO interface for table: User.
 * @author autogenerated
 */
public class UserDao extends GenericDao<Integer,User>  {

	/**
	 * 
	 */
	//private static final long serialVersionUID = 1L;
	/*
	@Transactional(rollbackFor=Exception.class)
	public User save(User user) throws EasyParkingException
	{
		if(user.getId()!=null) {
			merge(user);
		}else {
			persist(user);
		}
		return user;
	}
	// constructor only
	 * */
	 
}

