package com.easyparking.entity;


import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.Map;
import java.util.WeakHashMap;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.proxy.HibernateProxy;


/** 
 * Object mapping for hibernate-handled table: parking_lot.
 * @author autogenerated
 */

@Entity
@Table(name = "parking_lot")
public class ParkingLot extends BaseEntity<Integer> implements  Serializable {

	/** Serial Version UID. */
	private static final long serialVersionUID = -558968827L;


	/** Field mapping. */
	private String altitude;
	/** Field mapping. */
	private Integer availableCount;
	/** Field mapping. */
	private Date createdAt;
	/** Field mapping. */
	private String createdBy;
	/** Field mapping. */
	private Integer id = 0; // init for hibernate bug workaround
	/** Field mapping. */
	private String longitude;
	/** Field mapping. */
	private String name;
	/** Field mapping. */
	private Integer ownerId;
	/** Field mapping. */
	private Integer pickRate;
	/** Field mapping. */
	private Date pickTime;
	/** Field mapping. */
	private Integer regularRate;
	/** Field mapping. */
	private Integer totalCount;
	/** Field mapping. */
	private Date updatedAt;
	/** Field mapping. */
	private String updatedBy;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public ParkingLot() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public ParkingLot(Integer id) {
		this.id = id;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return ParkingLot.class;
	}
 

    /**
     * Return the value associated with the column: altitude.
	 * @return A String object (this.altitude)
	 */
	@Basic( optional = true )
	@Column( length = 250  )
	public String getAltitude() {
		return this.altitude;
		
	}
	

  
    /**  
     * Set the value related to the column: altitude.
	 * @param altitude the altitude value you wish to set
	 */
	public void setAltitude(final String altitude) {
		this.altitude = altitude;
	}

    /**
     * Return the value associated with the column: availableCount.
	 * @return A Integer object (this.availableCount)
	 */
	@Basic( optional = true )
	@Column( name = "available_count"  )
	public Integer getAvailableCount() {
		return this.availableCount;
		
	}
	

  
    /**  
     * Set the value related to the column: availableCount.
	 * @param availableCount the availableCount value you wish to set
	 */
	public void setAvailableCount(final Integer availableCount) {
		this.availableCount = availableCount;
	}

    /**
     * Return the value associated with the column: createdAt.
	 * @return A Date object (this.createdAt)
	 */
	@Basic( optional = true )
	@Column( name = "created_at"  )
	public Date getCreatedAt() {
		return this.createdAt;
		
	}
	

  
    /**  
     * Set the value related to the column: createdAt.
	 * @param createdAt the createdAt value you wish to set
	 */
	public void setCreatedAt(final Date createdAt) {
		this.createdAt = createdAt;
	}

    /**
     * Return the value associated with the column: createdBy.
	 * @return A String object (this.createdBy)
	 */
	@Basic( optional = true )
	@Column( name = "created_by", length = 250  )
	public String getCreatedBy() {
		return this.createdBy;
		
	}
	

  
    /**  
     * Set the value related to the column: createdBy.
	 * @param createdBy the createdBy value you wish to set
	 */
	public void setCreatedBy(final String createdBy) {
		this.createdBy = createdBy;
	}

    /**
     * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
    @Id 
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Basic( optional = false )
	@Column( name = "id", nullable = false  )
	public Integer getId() {
		return this.id;
		
	}
	

  

    /**
     * Return the value associated with the column: longitude.
	 * @return A String object (this.longitude)
	 */
	@Basic( optional = true )
	@Column( length = 250  )
	public String getLongitude() {
		return this.longitude;
		
	}
	

  
    /**  
     * Set the value related to the column: longitude.
	 * @param longitude the longitude value you wish to set
	 */
	public void setLongitude(final String longitude) {
		this.longitude = longitude;
	}

    /**
     * Return the value associated with the column: name.
	 * @return A String object (this.name)
	 */
	@Basic( optional = true )
	@Column( length = 250  )
	public String getName() {
		return this.name;
		
	}
	

  
    /**  
     * Set the value related to the column: name.
	 * @param name the name value you wish to set
	 */
	public void setName(final String name) {
		this.name = name;
	}

    /**
     * Return the value associated with the column: ownerId.
	 * @return A Integer object (this.ownerId)
	 */
	@Basic( optional = true )
	@Column( name = "owner_id"  )
	public Integer getOwnerId() {
		return this.ownerId;
		
	}
	

  
    /**  
     * Set the value related to the column: ownerId.
	 * @param ownerId the ownerId value you wish to set
	 */
	public void setOwnerId(final Integer ownerId) {
		this.ownerId = ownerId;
	}

    /**
     * Return the value associated with the column: pickRate.
	 * @return A Integer object (this.pickRate)
	 */
	@Basic( optional = true )
	@Column( name = "pick_rate"  )
	public Integer getPickRate() {
		return this.pickRate;
		
	}
	

  
    /**  
     * Set the value related to the column: pickRate.
	 * @param pickRate the pickRate value you wish to set
	 */
	public void setPickRate(final Integer pickRate) {
		this.pickRate = pickRate;
	}

    /**
     * Return the value associated with the column: pickTime.
	 * @return A Date object (this.pickTime)
	 */
	@Basic( optional = true )
	@Column( name = "pick_time"  )
	public Date getPickTime() {
		return this.pickTime;
		
	}
	

  
    /**  
     * Set the value related to the column: pickTime.
	 * @param pickTime the pickTime value you wish to set
	 */
	public void setPickTime(final Date pickTime) {
		this.pickTime = pickTime;
	}

    /**
     * Return the value associated with the column: regularRate.
	 * @return A Integer object (this.regularRate)
	 */
	@Basic( optional = true )
	@Column( name = "regular_rate"  )
	public Integer getRegularRate() {
		return this.regularRate;
		
	}
	

  
    /**  
     * Set the value related to the column: regularRate.
	 * @param regularRate the regularRate value you wish to set
	 */
	public void setRegularRate(final Integer regularRate) {
		this.regularRate = regularRate;
	}

    /**
     * Return the value associated with the column: totalCount.
	 * @return A Integer object (this.totalCount)
	 */
	@Basic( optional = true )
	@Column( name = "total_count"  )
	public Integer getTotalCount() {
		return this.totalCount;
		
	}
	

  
    /**  
     * Set the value related to the column: totalCount.
	 * @param totalCount the totalCount value you wish to set
	 */
	public void setTotalCount(final Integer totalCount) {
		this.totalCount = totalCount;
	}

    /**
     * Return the value associated with the column: updatedAt.
	 * @return A Date object (this.updatedAt)
	 */
	@Basic( optional = true )
	@Column( name = "updated_at"  )
	public Date getUpdatedAt() {
		return this.updatedAt;
		
	}
	

  
    /**  
     * Set the value related to the column: updatedAt.
	 * @param updatedAt the updatedAt value you wish to set
	 */
	public void setUpdatedAt(final Date updatedAt) {
		this.updatedAt = updatedAt;
	}

    /**
     * Return the value associated with the column: updatedBy.
	 * @return A String object (this.updatedBy)
	 */
	@Basic( optional = true )
	@Column( name = "updated_by", length = 250  )
	public String getUpdatedBy() {
		return this.updatedBy;
		
	}
	

  
    /**  
     * Set the value related to the column: updatedBy.
	 * @param updatedBy the updatedBy value you wish to set
	 */
	public void setUpdatedBy(final String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Override
	public void setId(Integer id) {
		
		this.id=id;
	}


   
	



	
}
